게시글 작성 기능
teamCleanie/ReFabBE pull request #15
Opened 2024-11-13 06:59 UTC by c0smosaur

## #️⃣연관된 이슈

#9 

## 📝작업 내용

- 게시글-사진 단방향 연관관계 (`PostEntity`, `PhotoEntity`)
- 요청 -> 엔티티, 엔티티 -> 응답 변형 로직`PostConverter`, `PhotoConverter` 클래스로 분리

- 사진 업로드 기능 
  - 게시글과 별개로 s3에 업로드하고 이미지 링크를 받아 저장, 삭제하며, 게시글 임시저장 및 저장 시 생성되는 `PostEntity`의 `PostId`를 `PhotoEntity`에 저장하여 게시글과 연결합니다.
- 게시글 임시저장/저장
  - `boolean` 필드를 두어 임시저장된 글인지, 저장된 글인지 구분하며, 원단 종류, 게시글 타입, 거래 방식은 `enum`으로 관리합니다.
  
- 사용자 부분이 추가되면 한번에 테스트를 작성하고자, 우선은 swagger 상에서 작동 확인만 해두었습니다.
- 사용자 기능이 추가되면 연관관계도 추가하고, 수정 들어갈 예정입니다. 

### 스크린샷 (선택)

## 💬리뷰 요구사항(선택)

- cloudfront를 사용해서 받아온 링크를 db에 저장하는 것 아니면 s3 링크를 저장해놓고 애플리케이션 단에서 가져올 때는 cdn 링크에서 가져오는 것 중 어느 것이 나을지 여쭤보고 싶습니다!

2024-11-13 07:46 UTC, seokheePark requested changes
빠르게 작업해주셔서 감사해요 :)

원래 서진님의 실력을 제가 몰라서였지만 되게 객체지향의 장점들을 살려서 코드를 작성하시려는 노력이 돋보여서 감동적이면서도 배울점이 많이 있던 코드 같아요!
개선할 수 있는 점이 조금 있어보여서 우선 RC를 드릴게요!

사실 지금도 충분히 잘 동작하는 좋은 코드, 좋은 PR임이 확실해서요! 오늘 저녁에 같이 이야기해보시고 개선이 필요없다고 느껴지신다면 다시 approve 하도록 하겠습니다!

고생 많으셨습니다~!

2024-11-13 07:46 UTC, seokheePark commented on src/main/java/cleanie/repatch/photo/component/PhotoValidator.java
`Validator` 클래스를 두시고 이 클래스에서 유효성 검증을 하고 계시네요!
만약 이부분을 실제 `Photo` 도메인 객체가 생성될 때 검증하도록 도메인 클래스로 로직을 이동시키는건 어떻게 생각하세요? 🤔

2024-11-13 07:46 UTC, seokheePark commented on src/main/java/cleanie/repatch/photo/component/PhotoValidator.java
> +        this.allowedExtensions = new HashSet<>(Set.of(".jpg", ".jpeg", ".png", ".webp"));
이부분은 `Enum` 을 쓰는건 어떨까요?!
재사용성도 좋아지고, 또 실수할 확률이 줄어들 수 있을 것 같아요!

2024-11-13 07:46 UTC, seokheePark commented on src/main/java/cleanie/repatch/photo/component/PostPhotoManager.java
> +    }
이미 `photoEntity` 는 영속성 컨텍스트에 저장되어있을 것 같은데 `@Transactional`을 사용 안하시고 바로 `repository.save`를 호출하신 의도가 있으신지 궁금해요!

2024-11-13 07:46 UTC, seokheePark commented on src/main/java/cleanie/repatch/photo/component/PostPhotoManager.java
전체적으로 `List<PhotoEntity>` 타입을 가지고 그 안에서 컬렉션을 조절하는 로직이 많아보여요!
이런 경우 `List<PhotoEntity>` 를 또 다른 일급 컬렉션 객체로 래핑해보는건 어떨까요?
- https://jojoldu.tistory.com/412 (일급 컬렉션이란?)

2024-11-13 07:46 UTC, seokheePark commented on src/main/java/cleanie/repatch/photo/component/PostPhotoManager.java
> +        }
하나의 메서드 안에 depth가 반복문 안에 `if-else` 문 까지 있어서 가독성이 떨어질 수 있을 것 같아요.
별도의 메서드로 분리하면 해당 반복문이나 조건문이 어떤 역할을 하는지 알 수 있고
메서드의 가독성도 좋아질 수 있을 것 같아요!

또 `if-else`문도 조기 return하는 방식으로 개선할 수 있을 것 같은데 어떠신가요?
- https://woonys.tistory.com/209 (Early return pattern)

2024-11-13 07:46 UTC, seokheePark commented on src/main/java/cleanie/repatch/photo/controller/PhotoController.java
> +    @Operation(summary = "사진 업로드", description = "사진을 s3에 업로드하고, 사진 id와 url을 반환합니다.")
오 이거 Operation하면 저희 docs에도 잘 생성되나요??? (이건 진짜 몰라서 궁금해요 ㅋㅋㅋㅋ)

2024-11-13 07:46 UTC, seokheePark commented on src/main/java/cleanie/repatch/common/s3/config/AwsS3Properties.java
>      }
단순 로깅을 위한 메서드는 없어도 좋을 것 같아요!
그리고 꼭 필요한 로깅을 위해선 `@Slf4j` 어노테이션을 활용해서 `log` 메서드를 사용하면 더 좋을 것 같아요!

이 부분은 에러가 많았던 부분인데 `PostConstruct`로 값들이 잘 주입되었는지 확인하는 방식은 너무 좋네요! 👍💯

2024-11-13 07:46 UTC, seokheePark commented on src/main/java/cleanie/repatch/photo/controller/PhotoController.java
> +    @DeleteMapping("/{photo_id}")
이 부분은 꼭 `SnakeCase` 가 아니어도 되지 않을까요?

2024-11-13 07:46 UTC, seokheePark commented on src/main/java/cleanie/repatch/photo/domain/PhotoEntity.java
> +@EntityListeners(AuditingEntityListener.class)
`JPA` 의 `Auditing` 기능을 활용해서 자동으로 `createdAt` 과 같은 컬럼이 관리되도록 한 점이 너무 좋아요!

이제 곧 `User` 도메인도 머지가 될테니, `createdAt`, `createdBy`, `updatedAt`, `updatedBy` 와 같은 컬럼을 `auditing`을 통해 관리하는 `BaseEntity` 클래스를 만들고 해당 엔티티를 상속하는 형태로 구현하면 좋을 것 같은데 같이 적용해보시면 어떨까요?

2024-11-13 07:46 UTC, seokheePark commented on src/main/java/cleanie/repatch/photo/domain/PhotoEntity.java
> +public class PhotoEntity {
음 현재 테이블 매핑을 담당하는 `Entity` 클래스와 도메인 객체를 나타내는 `Photo` 가 하나의 클래스에 책임이 되어있어서 `PhotoEntity` 라고 작명을 하신 것같아요! 의도가 드러나는 이름이라 너무 좋습니다!

두 객체를 구분해서 관리할 때에는 지금처럼 작명을해도 좋지만, 지금은 엔티티 객체 자체가 도메인 객체이기도 하니,
`Photo` 라는 이름으로 하면 더 명확하고 직관적일 것 같은데 어떻게 생각하세요?!

2024-11-13 07:46 UTC, seokheePark commented on src/main/java/cleanie/repatch/photo/model/request/PhotoUploadRequest.java
> +public record PhotoUploadRequest(
레코드의 사용 좋아요!
`Request`와 `Response` 같은 자료구조 책임을 갖는 객체를 레코드로 관리하니까
완전 간단하면서 한 눈에 책임을 알 수 있네요!

2024-11-13 07:46 UTC, seokheePark commented on src/main/java/cleanie/repatch/photo/service/PhotoService.java
> +        }
이 부분은 위에서 말한 조기리턴이 가능한 형태여서 이런식으로 고치면 어떨까요?
```suggestion
    @Transactional
    public boolean deletePhotoIfExistsById(Long id){
        if (photoRepository.existsById(id)){
            photoRepository.deleteById(id);
            return true;
        } 
        return false;
```

2024-11-13 07:46 UTC, seokheePark commented on src/main/java/cleanie/repatch/post/component/PostValidator.java
> +                !request.transactionTypes().isEmpty();
이렇게 `request` 를 검증하는 코드는 따로 `validator` 같은 클래스를 두기보다는
`@Valid` 어노테이션을 사용해서 검증 할 수 있을 것 같은데 어떠세요? 🤔

2024-11-13 07:46 UTC, seokheePark commented on src/main/java/cleanie/repatch/post/domain/enums/TransactionTypes.java
> +    private final Set<TransactionType> transactionTypes;
`TransactionType` 을 `Enum`으로 만들면서 해당 `Enum` 값들을 `Set` 으로 관리하고 거기다가 심지어 값 객체를 활용하여 일급 컬렉션 으로 감싼 부분은 진짜 너무 좋네요... 많이 배우고 갑니다 💯💯💯💯

다른 팁을 하나 드리자면 `Enum` 자체를 자료구조로 감쌀 때는 자바에서 제공해주는 전용 컬렉션이 따로 있어요!
큰 차이는 아니지만, 성능상의 이점이 있으니 이 자료구조들을 적용해보시면 어떨까요?
- https://mantaray.tistory.com/114 (Enum, EnumSet, EnumMap)

2024-11-13 07:46 UTC, seokheePark commented on src/main/java/cleanie/repatch/post/service/PostService.java
> +                () -> new BadRequestException(ExceptionCode.INVALID_REQUEST));
`BadRequestException`은 제가 만든 예시 커스텀 예외 클래스에요 ㅎㅎ
물론 이걸 직접 활용해도 요청이 잘못되었다는 예외를 잘 나타낼 수 있을 것 같아요!

`EntityNotFoundException` 같이 조금 더 명확한 예외를 만들고 그리고 예외 메시지도 조금 더 명확하게 하는건 어떨까요? 너무 자세한 예외는 취약점이 되기도 하지만, 일반적으로는 유지보수 하기 좋아져요.

특히 그런 DB 조회 시 나오는 예외들을 `ControllerAdvice` 클래스에서 예외처리 할때 4xx번대 상태 코드를 반환해서 더 Restful 하게 만들 수 있을 것 같아요 ㅎㅎ

2024-11-13 07:48 UTC, stoneHee99 requested changes
실수로 이상한 계정으로 리뷰를 남겼네요.. 죄송합니다...! 저 계정도 제가 작성한거여서 코멘트는 저쪽 참고해주시면 됩니다~!

고생 많으셨어요 😊👍

2024-11-13 08:42 UTC, c0smosaur commented on src/main/java/cleanie/repatch/common/s3/config/AwsS3Properties.java
>      }
로컬에서 확인한다고 넣었던 부분을 그대로 올려버렸네요..! 😅
로깅 관련해서는 `@Slf4j`를 더 사용하고, 이 부분은 제거하겠습니다 👍

2024-11-13 08:42 UTC, c0smosaur commented on src/main/java/cleanie/repatch/photo/component/PhotoValidator.java
검증 로직은 도메인 클래스 내부에서 처리하는 것도 괜찮을 것 같아요! 
`converter` 클래스들 안에서 `Builder`를 사용해 도메인 객체를 생성하고 있어서 검증도 분리해두었는데, 한번 수정해보겠습니다!

2024-11-13 08:42 UTC, c0smosaur commented on src/main/java/cleanie/repatch/photo/component/PostPhotoManager.java
안그래도 이 부분도 거래방식과 동일하게 처리하는 게 좋을지 고민하고 있었는데, 감사합니다! 수정해보도록 하겠습니다 👍

2024-11-13 08:42 UTC, c0smosaur commented on src/main/java/cleanie/repatch/photo/controller/PhotoController.java
> +    @Operation(summary = "사진 업로드", description = "사진을 s3에 업로드하고, 사진 id와 url을 반환합니다.")
`swagger` 문서에 엔드포인트마다 여기 넣은 값대로 설명이 붙더라구요!! 👍

2024-11-13 08:43 UTC, c0smosaur commented on src/main/java/cleanie/repatch/photo/controller/PhotoController.java
> +    @DeleteMapping("/{photo_id}")
그러네요!! `CamelCase`로 변경해두겠습니다! 👍

2024-11-13 08:43 UTC, c0smosaur commented on src/main/java/cleanie/repatch/photo/domain/PhotoEntity.java
> +@EntityListeners(AuditingEntityListener.class)
모든 엔티티가 `JpaAuditing`으로 생성되는 칼럼이 필요한 건 아닌 것 같아서 보류해두었는데, 
말씀하신 대로 엔티티가 늘어날테니 그렇게 관리하는 편이 더 좋을 것 같습니다! 
공통엔티티니 `common` 패키지 쪽에 생성해두고 상속하는 형태로 구현해 보겠습니다!

2024-11-13 08:43 UTC, c0smosaur commented on src/main/java/cleanie/repatch/photo/domain/PhotoEntity.java
> +public class PhotoEntity {
확인했습니다! 그러면 사진 엔티티명을 변경하고, 게시글도 동일하게 `PostEntity` -> `Post`로 변경하도록 할게요~!

2024-11-13 08:44 UTC, c0smosaur commented on src/main/java/cleanie/repatch/photo/service/PhotoService.java
> +        }
확인했습니다! 조기 리턴으로 수정하고, 다른 부분에도 조기 리턴이 가능한 부분이 있는지 살펴보겠습니다~!

2024-11-13 08:44 UTC, c0smosaur commented on src/main/java/cleanie/repatch/post/component/PostValidator.java
> +                !request.transactionTypes().isEmpty();
임시 저장을 할 때는 필드가 비어있어도 저장 가능해야 하다보니 `@Valid`를 사용하기보다는 따로 클래스를 생성하였는데, 
그럼 임시저장이 아니라 게시글 저장으로 들어왔을 때만 `@Valid`로 검증하면 될 것 같기도 하네요! 
한번 다시 확인해보겠습니다!

2024-11-13 08:44 UTC, c0smosaur commented on src/main/java/cleanie/repatch/post/domain/enums/TransactionTypes.java
> +    private final Set<TransactionType> transactionTypes;
석희님이 일급컬렉션을 알려주셔서 처음 사용해보았습니다 저야말로 감사합니다 ☺️
`Enum` 전용 컬렉션이 따로 있었군요! 알려주신 대로 적용해보도록 하겠습니다! 👍

2024-11-13 08:44 UTC, c0smosaur commented on src/main/java/cleanie/repatch/post/service/PostService.java
> +                () -> new BadRequestException(ExceptionCode.INVALID_REQUEST));
예시였군요 ㅎ... 조금 더 자세한 커스텀 예외들을 생성하여 활용해보도록 하겠습니다!

2024-11-13 08:45 UTC, c0smosaur reviewed
자세한 리뷰해주시고 개선점도 짚어주셔서 감사합니다! 👍💯
말씀해주신 부분 수정하도록 할게요~!!

2024-11-13 09:04 UTC, c0smosaur commented on src/main/java/cleanie/repatch/photo/component/PostPhotoManager.java
> +    }
`toBuilder`를 사용해서 원래 값을 가진 새로운 엔티티를 생성하여 값을 수정하기 때문에 `save`를 호출하고 있습니다..!

2024-11-13 09:04 UTC, c0smosaur commented on src/main/java/cleanie/repatch/photo/component/PhotoValidator.java
> +        this.allowedExtensions = new HashSet<>(Set.of(".jpg", ".jpeg", ".png", ".webp"));
앗,.. ! 코멘트 남긴 줄 알았는데 날아갔네요 ㅠ 
`enum`으로 수정하는 게 훨씬 좋아보입니다! 수정에 반영하도록 할게요~!

2024-11-13 09:05 UTC, c0smosaur commented on src/main/java/cleanie/repatch/photo/component/PostPhotoManager.java
> +        }
확실히 가독성이 떨어져보이네요..! 
감사합니다! 전달해주신 링크 참고하여 수정해보도록 하겠습니다!

2024-11-13 09:12 UTC, stoneHee99 commented on src/main/java/cleanie/repatch/photo/component/PostPhotoManager.java
> +    }
오~! 그러면 필요한 값은 업데이트하고 필요하지 않은 값은 기존의 객체에서 복사해서 새로운 객체를 만든다는 말씀이신가요?!

제가 지금 한눈에 파악하기 어려웠던 것처럼 해당 메서드가 의도를 나타내기 어려운 것 같아요.
이 부분은 `정적 팩토리 메서드` 패턴을 적용해서 `copyToUpdatedPhoto` 와 같은 생성 메서드를 만들어보는건 어떨까요?

- https://sun-22.tistory.com/84 (이펙티브 자바 아이템 1. 정적 팩토리 메서드 패턴을 고려하라)

2024-11-13 09:16 UTC, stoneHee99 commented on src/main/java/cleanie/repatch/photo/service/PhotoService.java
> +        }
해당 부분은 어차피 id가 있으니, `findById` 로 직접 select를 해와서 해당 entity를 delete 하는 식으로 하면 더 직관적일 것 같은데 어떻게 생각하세요?

2024-11-13 09:20 UTC, stoneHee99 commented on src/main/java/cleanie/repatch/post/component/PostValidator.java
> +                !request.transactionTypes().isEmpty();
아하 그런 요구사항을 만족시키기 위해서 저렇게 따로 validate를 하셨군요!
충분히 일리 있는 구현인 것 같아요!

다만, validate 로직을 객체와 나누면 생기는 단점들이 너무 많아요!
차라리, 임시 게시글 객체와 실제 게시글 객체를 나눠보는건 어떨까요?

실제 다른 테이블로 구성하여도 좋고, 아니면 하나의 테이블에서 Type에 따라 분류하되 JPA를 활용하여 객체는 나누어 매핑되도록 구성할 수도 있을 것 같아요!
그러면, 각각 도메인 생성자가 나뉘기 때문에 validation도 더 쉬울 것 같아요! 
각 도메인에 따른 로직이 나누어져 있어도, 각 책임에 맞게 더 응집도 있는 객체가 될 수도 있을 것 같구요!
또, `임시 게시글은 게시글로 변경할 수 있지만, 이미 등록된 게시글은 임시 게시글이 될 수 없다` 라는 요구사항도 구현하기 쉬울 것 같은데 어떠세요?

2024-11-15 00:57 UTC, stoneHee99 approved these changes
리뷰사항 잘 반영해주셔서 정말 감사드립니다 :)

점점, 더 코드가 개선되고 깨끗해지면서 저도 모르게 욕심이 생겨 과도한 요구를 드린건 아닐까 모르겠어요! 현재도 좋은 구조이지만, 역시 개선할 수 있는 점들이 보여서 리뷰를 추가로 남겼어요.

지금도 충분히 좋은 구조이니, 우선 approve 하도록 하겠습니다! 개선이 필요하다고 생각이 드시면 반영해주셔도 되고 아니면 그냥 머지하셔도 될 것 같아요 👍 

수고하셨습니다! LGTM 💯 💯 🥇

2024-11-15 00:57 UTC, stoneHee99 commented on src/main/java/cleanie/repatch/common/exception/model/ExceptionCode.java
> +    DRAFT_NOT_FOUND(2110, "임시저장된 글을 찾을 수 없습니다."),
`ExceptionCode`는 말 그대로 어플리케이션 내에서 발생하는 모든 에러 메시지를 관리하는 `Enum` 클래스 입니다.
`INVALID_VALUE` 같은 메시지는 에러 메시지를 받아보는 사용자 혹은 프론트엔드 개발자 입장에서 명확하지 않다고 느껴질 수 있을 것 같아요!

`21xx` 번대 오류는 게시글 관련 오류로 관리하고자 하셨으니, 조금 더 게시글 도메인에 맞는 에러 메시지를 전달하면 의도가 명확히 드러나지 않을까요? `DRAFT_NOT_FOUND` 메시지도 그런 느낌으로 개선할 수 있을 것 같아요!

만약 특정 도메인에 종속되지 않고, 전역적으로 사용이 필요한 예외 코드가 있다면 관리하기 쉽도록 `10xx` 번대나 `99xx` 번대 예외로 선언해서 관리가 용이하게 하면 좋을 것 같아요!

2024-11-15 00:57 UTC, stoneHee99 commented on src/main/java/cleanie/repatch/draft/controller/DraftController.java
> +    // 게시글 개별 조회
해당 주석은 아래 `@Operation` 어노테이션과 역할이 겹치는 것 같아요!
하나로 줄일 수 있지 않을까요?

2024-11-15 00:57 UTC, stoneHee99 commented on src/main/java/cleanie/repatch/draft/controller/DraftController.java
> +    }
이부분도 조기에 리턴하는 식으로 개선해보면 어떨까요?
더 나아가서, 컨트롤러에서 `if-else` 문으로 분기처리 하는 것보다 `draftService.deleteDraftById(draftId)` 로직 내에서 직접 예외를 내보내는게 더 직관적일 것 같은데 어떠세요?

2024-11-15 00:57 UTC, stoneHee99 commented on src/main/java/cleanie/repatch/draft/domain/Draft.java
> +public class Draft extends BaseEntity {
`Draft` 라는 이름이 임시저장이라는 의도는 명확히 드러나지만, 추후에 임시 저장 할 수 있는 다른 데이터가 생기는 요구사항이 들어오면, 어려움이 있을 수 있을 것 같아요!

`DraftPost` 등으로 조금 더 의도가 드러나는 작명을 해보는 건 어떨까요?

2024-11-15 00:57 UTC, stoneHee99 commented on src/main/java/cleanie/repatch/draft/domain/Draft.java
> +
값 객체의 적절한 사용으로 `Draft` 라는 객체가 너무 가독성 좋아졌어요! 💯💯💯

2024-11-15 00:57 UTC, stoneHee99 commented on src/main/java/cleanie/repatch/draft/domain/Draft.java
> +    }
`updateDraft` 메서드가 직접 값을 업데이트 하는게 아닌 새로운 객체를 반환하는 의도가 있으실까요?

2024-11-15 00:57 UTC, stoneHee99 commented on src/main/java/cleanie/repatch/draft/domain/Draft.java
> +    }
`Draft` 도메인 안에 도메인 로직이 있으니까 각 도메인의 책임이 명확해져서 너무 좋네요!

지금도 너무 좋은 구현이지만 의견을 덧붙여 볼게요. 이부분은 참고만 해주셔도 좋아요!
`toDraftResponse`같은 메서드는 매개변수로 `Draft` 객체를 받고 있어요. 
그러다보니 자연스럽게 `getter` 메서드를 통해 속성을 꺼내오게 되요.
그렇게 하기보단 직접 해당 객체에 메서드를 통해서 `this.id,` `this.postType` 등으로 꺼내오면 어떨까요?

`Entity`는 데이터 영속화 등을 위해 `getter` 메서드가 거의 필수 처럼 되어있지만, 그럼에도 불구하고 불필요한 `getter` 의 사용은 지양하는게 어떨까요?

그리고 지금과 같은 구조면 `Draft` 내에 여러 `Response`로 변환하는 코드로 가득 가득해질 것 같은데 어떻게 개선할 수 있을지도 같이 고민해보면 좋을 것 같아요!

2024-11-15 00:57 UTC, stoneHee99 commented on src/main/java/cleanie/repatch/draft/service/DraftService.java
> +    }
`viewDraft` 메서드는 단순히 조회의 책임을 가진 메서드에요.
그럴 떄는 `@Transactional(readonly = true)` 로 설정해서, 데이터베이스에게 힌트를 전달하는건 어떨까요?

2024-11-15 00:57 UTC, stoneHee99 commented on src/main/java/cleanie/repatch/draft/service/DraftService.java
> +                () -> new BadRequestException(ExceptionCode.DRAFT_NOT_FOUND));
조회하는 부분이 여러 메서드에서 겹치는 것 같아요!
별도의 메서드로 분리해서 중복을 줄여보는건 어떨까요?

2024-11-15 00:57 UTC, stoneHee99 commented on src/main/java/cleanie/repatch/photo/controller/PhotoController.java
> +            throw new BadRequestException(ExceptionCode.FILE_NOT_FOUND);
이 코드도 위에서 리뷰드린 방법으로 개선해보면 좋을 것 같아요!

2024-11-15 00:57 UTC, stoneHee99 commented on src/main/java/cleanie/repatch/photo/domain/Photo.java
`Photo` 엔티티는 기존 요구사항과 다르게 조금 더 이미지, 그리고 게시글과의 연관성이 부각된 도메인 같아 보여요!
단순한 사진 파일이 아닌 게시글과 연관이 있다는 식으로 작명을 변경해보면 어떨까요?

2024-11-15 00:57 UTC, stoneHee99 commented on src/main/java/cleanie/repatch/post/domain/Post.java
> +                && !request.transactionTypes().isEmpty();
이부분은 `Post`를 검증하는 부분이 아닌, `PostRequest` 객체를 검증하는 부분이니까, `PostRequest`가 생성될 때 검증하는게 더 깔끔할 것 같은데 어떠세요?

2024-11-15 00:57 UTC, stoneHee99 commented on src/main/java/cleanie/repatch/post/domain/Post.java
> +        }
`validatePost` 라는 메서드명은 `게시글을 검증한다` 라는 의미를 나타내니까 `validatePost`는 반환 값이 없이 메서드 내부에서 예외를 던지는게 더 자연스럽지 않을까요?
만약 해당 게시글이 유효한지 아닌지를 불리언 타입으로 나타내는 메서드라면 `isValidPost` 같은 이름이 더 적절할 것 같은데 어떠세요?

2024-11-15 01:00 UTC, stoneHee99 commented
conflict 나는 부분이 있어서 제가 머지했는데 다음과 같은 부분이에요 `ExceptionCode`, `build.gradle`, `application.yml` 누락 사항은 없는지 확인 부탁드려요!

2024-11-18 06:37 UTC, c0smosaur commented on src/main/java/cleanie/repatch/common/exception/model/ExceptionCode.java
> +    DRAFT_NOT_FOUND(2110, "임시저장된 글을 찾을 수 없습니다."),
원단 타입이나 거래 방식 등 `enum`으로 처리하는 값들 중 일치하지 않는 값이 들어오면 사용하려고 작성한 기억이 있네요..! 
확실히 모호한 메시지라서 수정이 필요해보입니다! 🥹👍 검증 부분에서 처리할 수 있는 부분같아 확인해보겠습니다.
추가로, 엔티티를 찾지 못하는 경우는 공통으로 선언하도록 수정해둘게요!! 👍

2024-11-18 06:37 UTC, c0smosaur commented on src/main/java/cleanie/repatch/draft/domain/Draft.java
> +    }
JPA 영속성 컨텍스트 내에서 처리를 하는 부분이니 필요가 없는 게 맞습니다..! 
놓친 부분을 짚어주셔서 감사해요! 수정 들어가겠습니닷 👍

2024-11-18 06:37 UTC, c0smosaur commented on src/main/java/cleanie/repatch/draft/domain/Draft.java
> +    }
엔티티 내부에 메서드가 있으니 `this`를 사용할 수 있다는 장점이 있네요! 
참고하여 수정하도록 하겠습니다. 감사합니다 ☺️

2024-11-18 06:37 UTC, c0smosaur commented on src/main/java/cleanie/repatch/photo/domain/Photo.java
확인했습니다! 그렇다면 `Photo`에서 `PostPhoto'로 변경하도록 하겠습니다! 💯👍

2024-11-18 06:37 UTC, c0smosaur commented on src/main/java/cleanie/repatch/post/domain/Post.java
> +                && !request.transactionTypes().isEmpty();
맞습니다..! 
사실 게시글과 임시저장글의 서로 다른 요구사항 때문에 도메인이 2개로 나뉘었다보니 
각각 검증 과정을 적용할 수 있는데 이 부분을 제가 반영하는 것을 누락했네요 🥲
말씀하신 대로 `PostRequest`를 검증하는 부분이다보니, 
`@NotBlank`와 `@Valid` 애너테이션으로 대체할 수 있을 것 같습니다! 👍👍

2024-11-18 06:52 UTC, stoneHee99 commented
다소 난해한 피드백이었는데 잘 반영해주셔서 정말 감사드립니다! 개선된 코드를 보니 훯씬 더 가독성있고, 변경에도 능한 코드가 되어가는 것 같아서 제가 다 뿌듯하네요!

특히 `EnumIterableValidator` 를 통해 `Enum` 에 대한 유효성 검사를 더 엄격히 한 점이 인상적이었어요. `Enum` 클래스에 대해서 저는 `@NotNull` 정도로만 체크하고 넘어가는 스타일이었는데 많이 배웠습니다! 

이 pr은 이만 머지할게요! 정말 고생많으셨습니다!

2024-11-18 06:53 UTC, merged